DROP DATABASE IF EXISTS book;

CREATE DATABASE book;

USE book;

CREATE TABLE t_user(
	id INT PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(20) NOT NULL UNIQUE,
	PASSWORD VARCHAR(30) NOT NULL,
	email VARCHAR(200)
);

INSERT INTO t_user(username,PASSWORD,email) VALUES(
	'root','123456','123@q.com'
);


SELECT * FROM t_user;